# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb994c8548b68afec9719473b5f3a01931677e4ebc06c760d4613ab98141fd1cddc8276758db80b60bb02acbb93046469a2b4f05f45768415050c83324fd9233

test:
  secret_key_base: dde50c2e93fff6bd86dac01957714d42f0098c1a96746265d7a7a016b9ac3c247a36d41fbe253b95a92d4149a2df560379d14084189ec11e7cca72c02bcf9517

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
